version: "3.7"

services:
  # Service untuk container item-app
  item-app:
    image: puttriipus/item-app:v1
    command: npm start
    ports:
      - "80:8080"
    depends_on:
      - item-db
    restart: always

  # Service untuk container item-db
  item-db:
    image: mongo:3
    restart: always
    ports:
      - 27017:27017
    volumes:
      - app-db:/data/db

volumes:
  # Volume untuk item-db
  app-db:
