version: 2.1

jobs:
  lint-dockerfile:
    docker:
      - image: hadolint/hadolint:latest
    steps:
      - checkout
      - run:
          name: Lint Dockerfile
          command: |
            find . -type f -name 'Dockerfile*' | xargs hadolint

  test-app:
    docker:
      - image: golang:latest
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Push Docker Image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u puttriipus --password-stdin
            docker build -t puttriipus/karsajobs:latest .
            docker push puttriipus/karsajobs:latest

workflows:
  version: 2
  build:
    jobs:
      - lint-dockerfile
      - test-app
      - build-app-karsajobs:
          filters:
            branches:
              only:
                - karsajobs
