version: 2.1

jobs:
  lint-dockerfile:
    docker:
      - image: hadolint/hadolint:latest
    steps:
      - checkout
      - run:
          name: Lint Dockerfile
          command: |
            find . -type f -name 'Dockerfile*' | xargs hadolint

  build-app-karsajobs-ui:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Push Docker Image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u puttriipus --password-stdin
            docker build -t puttriipus/karsajobs-ui:latest .
            docker push puttriipus/karsajobs-ui:latest

workflows:
  version: 2
  build:
    jobs:
      - lint-dockerfile
      - build-app-karsajobs-ui:
          filters:
            branches:
              only:
                - karsajobs-ui
